#!/bin/sh
### BEGIN INIT INFO
# Provides:          stone
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: stone
# Description:       Starts stone
#                    
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. $STONE_ENV

# PATH should only include /usr/* if it runs after the mountnfs.sh script
DESC="stone"
NAME=$APPLICATION_NAME
SCRIPTNAME=/etc/init.d/$NAME
RUNASUSER=$GEMSTONE_USER
STONE_ENV=$APPLICATION_DIR/env

# exit if no user is set
if [ ! $RUNASUSER ] ;  
then 
    echo  "RUNASUSER NOT SET" 
    exit 3 
fi

# source the seaside environment if it exists
if [ ! -r $STONE_ENV ] ;
then
    echo "Seaside ENV script doesnt exists at $STONE_ENV"
    exit 3
fi 

. $STONE_ENV

# Function that starts the daemon/service
do_start()
{
  if [ ! -d "$GEMSTONE_LOGDIR/old" ];
  then
      mkdir "$GEMSTONE_LOGDIR/old" > /dev/null 2>&1
  fi
  mv $GEMSTONE_LOGDIR/* "$GEMSTONE_LOGDIR/old" > /dev/null 2>&1
  su -m $RUNASUSER -c '$GEMSTONE_INSTALLATION/bin/startstone -z $GEMSTONE_SYS_CONF -l $APPLICATION_LOG_DIR/log.txt $APPLICATION_NAME' > $GEMSTONE_LOGDIR/startup.log 2>&1

}

# Function that stops the daemon/service
do_stop()
{
   su -m $RUNASUSER -c '$GEMSTONE_INSTALLATION/bin/stopstone -i $APPLICATION_NAME DataCurator swordfish' > $GEMSTONE_LOGDIR/shutdown.log 2>&1
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && echo "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] &&  exit 0 ;;
		3) [ "$VERBOSE" != no ] && echo "failed" && exit 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && echo "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && exit 0 ;;
		2) [ "$VERBOSE" != no ] && exit 1 ;;
	esac
	;;

  restart|force-reload|reload)
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias

	echo "Restarting $DESC" "$NAME" "NO Reload for $NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) exit 0 ;;
			1) exit 1 ;; # Old process is still running
			*) exit 1 ;; # Failed to start
		esac
		;;

	  *)
	  	# Failed to stop
		exit 1
		;;
	esac
	;;

  status)
        /opt/gemstone/product/bin/gslist -lcv
        exit 3
        ;;
  *)
	log_action_msg "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload|status}" >&2
	exit 3
	;;
esac

:
